# -*- coding: utf-8 -*-
"""ML-AZ_MultipleLinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15iosgdGmX-VL61f0IM0cQDR6_Xmr0O9w

<h2>Importing the libraries</h2>
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""<h2>Importing the dataset</h2>"""

dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

"""<h2>Encoding categorical data</h2>"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

"""<h2>Splitting the dataset into the training set and the test set</h2>"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

"""<h2>Training the Multiple Linear Regression model on the training set</h2>"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

"""<h2>Predicting the Test set results</h2>"""

y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))